# Generated by Django 2.1.8 on 2019-04-15 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('desc', models.TextField(blank=True)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
