# Generated by Django 2.1.8 on 2019-05-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190513_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='attachedfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
