# Generated by Django 2.1.8 on 2019-05-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_attachedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='attachedfile',
        ),
    ]
